### ISSUE TITLE
The reply is garbled in chinese

### ISSUE THREAD

**Issue by Scorpio-Gyh** [abi/secret-llama#10]
In tinyLlama, I asked him if he knew about webgpu, and the answer is follows, probably a font or coding problem
![image](https://github.com/abi/secret-llama/assets/59963334/8261f30b-c60e-486d-a389-c2a88807af34)

**Comment by abi** [comment]
Did you try the other models too?

**Comment by Scorpio-Gyh** [comment]
i test 4 models,Llama 3 and Mistral 7B are good, tinyLlama and Phi 1.5 have some problems
![image](https://github.com/abi/secret-llama/assets/59963334/5231af4c-2f3c-431f-b82a-3038d4db573b)

**Comment by abi** [comment]
Nice, thanks for testing. 

Going to close this because I'm going to replace Phi 1.5 with Phi 3 and TinyLlama is not a great model, only included because it's the fastest to download.

**Comment by abi** [comment]
Mistral and Llama 3 are the recommended models.
