### ISSUE TITLE
Error: Could not load the model because Error: Cannot find adapter that matches the request

### ISSUE THREAD

**Issue by K0-RR** [abi/secret-llama#16]
I'm getting this with every model `Could not load the model because Error: Cannot find adapter that matches the request`

**Comment by abi** [comment]
Which browser and OS are you on?

**Comment by RicoFio** [comment]
I'm getting the same on Brave [Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)] and Google Chrome [Version 121.0.6167.139 (Official Build, ungoogled-chromium) (64-bit)]

**Comment by abi** [comment]
Which OS are you on?

**Comment by RicoFio** [comment]
| Specification    | Value         |
|------------------|---------------|
| OS Name          | Pop!_OS 22.04 LTS |
| OS Type          | 64-bit        |
| GNOME Version    | 42.9          |
| Windowing System | X11           |

**Comment by abi** [comment]
I don't think WebGPU works on Linux. I could be wrong though.

**Comment by K0-RR** [comment]
> I don't think WebGPU works on Linux. I could be wrong though.

It appears to work when enabled manually via flags: [brave://flags/#enable-vulkan](brave://flags/#enable-vulkan) and [brave://flags/#enable-unsafe-webgpu](brave://flags/#enable-unsafe-webgpu). Sadly the performance is like 100x slower than when I use ollama on desktop (in browser it prints one character per 10 seconds so rather unusable).

Status can be checked on brave://gpu/
https://github.com/gpuweb/gpuweb/wiki/Implementation-Status
