### ISSUE TITLE
Could not load the model because TypeError: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by nephaste** [abi/secret-llama#6]
Hi thanks for this project

I compiled successfully and all start fine but i ask something in ui i am getting :

Could not load the model because TypeError: crypto.randomUUID is not a function

tried with nodejs18 and nodejs20 ... got same issue

![image](https://github.com/abi/secret-llama/assets/3392684/a55457c9-4bbd-4579-89dc-c598b8ea3034)

Do you have any clue ? I am stuck

**Comment by alecdwm** [comment]
What web browser are you using?

You'll need one that supports [crypto.randomUUID](https://caniuse.com/mdn-api_crypto_randomuuid) as well as [WebGPU](https://caniuse.com/webgpu)

**Comment by nephaste** [comment]
tried on opera, Firefox and chrome as well ...

the online demo works fine on all the browser ... i am a bit lost

**Comment by abi** [comment]
@nephaste does https://secretllama.com work but running locally doesn't work?

**Comment by nephaste** [comment]
yes exactly... i tested into an Ubuntu LXD container also on a Qnap NAS ... got same problem

**Comment by abi** [comment]
That is really strange. I wonder if it has to do with running in non-secure context HTTP locally vs. HTTPS on the demo website.

I assume you've tried, but did you delete the entire code folder and retried it from scratch? Could be a yarn installation issue.

**Comment by nephaste** [comment]
not tried in https, goal is to provide a QPKG for Qnap NAS
not sure how i can start secretllama over https with yarn build-and-preview 

i tried two way, with cross compiling (thinking it was a libc issue or a GCC issue on my dev environment) ,and without ... same result below the script use with cross compilation with my toolchain

my compile script is easy for cross compiling to be on same libc of the NAS Qnap and code can be executed

export PREFIX=/opt/SecretLLama

rm -rf /opt/SecretLLama
mkdir -p /opt/SecretLLama
cd /opt/SecretLLama


## export some flags for cross compiling with toolchain

export npm_config_build_from_source=true
export CC=${HOST}-cc
export CXX=${HOST}-g++

#######################
echo "extract NodeJS" in PREFIX
#######################

tar -xvf /opt/NodeJS18/archive.tgz -C $PREFIX

####################
echo "Prepare env"
####################

mkdir -p /opt/SecretLLama/lib_elf

### Copy stdc++ lib required to start nodejs

cp /DATA/x-tools/x86_64-QNAPGCC8-linux-gnu/x86_64-QNAPGCC8-linux-gnu/sysroot/lib/libstdc++.so.6.0.25 /opt/SecretLLama/lib_elf/libstdc++.so.6

## use nodeJS from Prefix and added it to PATH for runtime build

export PATH=/opt/SecretLLama/bin:$PATH

#add yarn to prefix

/opt/SecretLLama/bin/npm install -g yarn --prefix /opt/SecretLLama/ ;

# clone repo

git clone --recursive https://github.com/abi/secret-llama.git
cd secret-llama

### use python 3.11 from Apache83 QPKG in case of need

export PATH=/opt/SecretLLama/bin:/opt/Apache83/bin:$PATH
export PYTHON=/opt/Apache83/bin/python3

### start compiling

CC=${HOST}-gcc CXX=${HOST}-g++ npm_config_build_from_source=true /opt/SecretLLama/bin/yarn ;

### start secretllama

export LD_LIBRARY_PATH=/opt/SecretLLama/lib_elf:$LD_LIBRARY_PATH

CC=${HOST}-gcc CXX=${HOST}-g++ npm_config_build_from_source=true /opt/SecretLLama/bin/yarn build-and-preview ;

**Comment by Lennart00** [comment]
I run into the same Issue on Archlinux.

**Comment by nephaste** [comment]
then no way to start it in https and to provide a cert and key certificate (even a self signed one) ?

**Comment by alecdwm** [comment]
If you have a self signed cert, you can add it to the vite config like this:

```diff
diff --git a/vite.config.ts b/vite.config.ts
index bf12e0d..9839a09 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -2,10 +2,17 @@ import { defineConfig } from "vite";
 import react from "@vitejs/plugin-react";
 import checker from "vite-plugin-checker";
 import path from "path";
+import fs from "fs";
 
 // https://vitejs.dev/config/
 export default defineConfig({
   plugins: [react(), checker({ typescript: true })],
+  server: {
+    https: {
+      key: fs.readFileSync("key.pem"),
+      cert: fs.readFileSync("cert.pem"),
+    },
+  },
   resolve: {
     alias: {
       "@": path.resolve(__dirname, "./src"),
```

Vite will then serve the app over https when you run `yarn build-and-preview`!

**Comment by nephaste** [comment]
thanks will give a try ... do you plane to modfify the code itself ?

that we can add our own certs to Secretllama ?

Generally, i check and export CERT and KEY location to add it on startup command line

### Check if MyQnapCloud Lets Encrypt/SSL certificate exists

if [ -f /mnt/ext/opt/QcloudSSLCertificate/cert/cert ]

then 

echo "Found MyQnapCloud Lets Encrypt/SSL certificate and use it"

export CERT=/mnt/ext/opt/QcloudSSLCertificate/cert/cert
export KEY=/mnt/ext/opt/QcloudSSLCertificate/cert/key

else

echo "MyQnapCloud Lets Encrypt/SSL certificate not found, i am using self-signed certificate from QTS"

export CERT=/etc/stunnel/backup.cert
export KEY=/etc/stunnel/backup.key

fi

**Comment by Lennart00** [comment]
I managed to get it to work with an SSL proxy.

**Comment by nephaste** [comment]
Works great behind a ssl-proxy  thanks a lot for your help

![image](https://github.com/abi/secret-llama/assets/3392684/474973c5-6e06-4f14-9f22-36a3d9ce726d)
