### ISSUE TITLE
Could not load the model | Error: ArtifactIndexedDBCache failed to fetch.

### ISSUE THREAD

**Issue by dev-xo** [abi/secret-llama#7]
Hello @abi! First of all, amazing work!

I'm getting the following error, locally by initializing the repository on my workspace, and also from [secretllama.com](https://secretllama.com/).
- Model: Llama 3
- Other Models seems to work.

I've tried cleaning the cache and deleting browser data related to the page, sadly no effect.
- Probably a HuggingFace issue, as the error seems to indicate?

Thanks!
```
Could not load the model because Error: ArtifactIndexedDBCache failed to fetch: https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC/resolve/main/params_shard_2.bin
```
![1](https://github.com/abi/secret-llama/assets/82425492/a1970291-a3ed-4068-942d-cdf898fa3915)

**Comment by abi** [comment]
How'd you fix it?

**Comment by dev-xo** [comment]
Didn't, just closed it as there was not interest into the issue.
- Let me know if there is some update on it.
